import importlib
import json
from types import SimpleNamespace
from pathlib import Path

import pytest

from agent.generation_graph.orchestrator.planner import deterministic_contracts
from agent.generation_graph.graph import generation_graph
from agent.generation_graph.state import GenerationState

pytestmark = pytest.mark.anyio


def _load_generation_fixture(tmp_path: Path) -> dict:
    fixture_path = (
        Path(__file__).parents[2]
        / "src"
        / "agent"
        / "generation_graph"
        / "fixtures"
        / "generation_confirmed_session.json"
    )
    fixture = json.loads(fixture_path.read_text())
    fixture["artifact_workspace"] = str(tmp_path / "artifact_workspace")
    return fixture


async def test_generation_graph_skips_asset_agent_when_assets_are_code_generated(
    tmp_path: Path,
) -> None:
    fixture = _load_generation_fixture(tmp_path)
    fixture["uploaded_assets"] = []
    fixture["material_usage"] = {"assets": []}

    result = await generation_graph.ainvoke(fixture)

    assert result["generation_status"] == "succeeded"
    assert result["status"] == "succeeded"
    manifest_paths = {item["target_path"] for item in result["asset_manifest_plan"]}
    processed_paths = {item["target_path"] for item in result["processed_assets"]}
    assert manifest_paths == {"assets/cover.png"}
    assert processed_paths == {"assets/cover.png"}
    assert result["code_artifacts"]["referenced_asset_paths"] == []
    assert result["manifest_draft"]["cover"] == "assets/cover.png"
    assert result["debug_report"]["attempted"] is True
    assert result["debug_report"]["unresolved_issues"] == []
    assert result["validation_report"]["valid"] is True
    assert result["artifact_result"]["manifest_path"].endswith("manifest.json")
    assert result["draft_game_meta"]["cover_path"] == "assets/cover.png"
    assert [log["step"] for log in result["agent_logs"] if log["level"] == "info"]


async def test_generation_graph_generates_assets_before_debug_when_visual_assets_needed(
    tmp_path: Path,
) -> None:
    fixture = _load_generation_fixture(tmp_path)

    result = await generation_graph.ainvoke(fixture)

    processed_paths = {item["target_path"] for item in result["processed_assets"]}
    manifest_paths = {item["target_path"] for item in result["asset_manifest_plan"]}
    referenced_paths = set(result["code_artifacts"]["referenced_asset_paths"])

    assert result["generation_status"] == "succeeded"
    assert result["status"] == "succeeded"
    assert manifest_paths == {
        "assets/background.png",
        "assets/player.png",
        "assets/cover.png",
    }
    assert processed_paths == {
        "assets/background.png",
        "assets/player.png",
        "assets/cover.png",
    }
    assert referenced_paths == {"assets/background.png", "assets/player.png"}
    assert result["manifest_draft"]["cover"] == "assets/cover.png"
    assert result["debug_report"]["attempted"] is True
    assert result["debug_report"]["unresolved_issues"] == []
    assert result["validation_report"]["valid"] is True
    assert result["artifact_result"]["asset_paths"] == [
        "assets/background.png",
        "assets/player.png",
    ]
    assert result["draft_game_meta"]["title"]


async def test_draft_game_code_uses_configured_provider_when_not_mock(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    graph_module = importlib.import_module("agent.generation_graph.graph")
    fixture = _load_generation_fixture(tmp_path)
    state = GenerationState(**fixture)
    contracts = deterministic_contracts(state)
    state.development_brief = contracts["development_brief"]
    state.asset_manifest_plan = []
    state.game_spec = contracts["game_spec"]

    class RecordingCodingProvider:
        def __init__(self) -> None:
            self.calls = []

        def complete_json(self, **kwargs):
            self.calls.append(kwargs)
            return {
                "index_html": "<!doctype html><html><head><link rel='stylesheet' href='style.css'></head><body><canvas id='game'></canvas><script src='game.js'></script></body></html>",
                "style_css": "body{margin:0}",
                "game_js": "console.log('REAL_PROVIDER_SENTINEL');",
                "coding_notes": ["generated by configured provider"],
            }

    provider = RecordingCodingProvider()
    seen_config_kwargs = {}

    class NonMockProviderConfig:
        @classmethod
        def from_env(cls, **kwargs):
            seen_config_kwargs.update(kwargs)
            return SimpleNamespace(provider="openai-compatible")

    monkeypatch.setattr(graph_module, "ProviderConfig", NonMockProviderConfig, raising=False)
    monkeypatch.setattr(graph_module, "provider_from_config", lambda config: provider, raising=False)

    update = graph_module.draft_game_code(state)

    assert seen_config_kwargs == {
        "model_env_name": "CODING_AGENT_MODEL",
        "fallback_model_env_name": "OPENAI_COMPATIBLE_MODEL",
    }
    assert provider.calls
    game_js = Path(update["code_artifacts"]["game_js_path"]).read_text(encoding="utf-8")
    assert "REAL_PROVIDER_SENTINEL" in game_js


async def test_generation_graph_finalizes_failure_when_validator_rejects_bundle(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from agent.generation_graph.validator_agent import validate_final_delivery as real_validate

    def reject_without_repair(state):
        update = real_validate(state)
        update["validation_report"] = {
            "valid": False,
            "issues": [{"kind": "missing_cover", "path": "assets/cover.png"}],
        }
        update["generation_status"] = "failed"
        update["failed_step"] = "validator_agent"
        update["error_message"] = "最终验收失败：missing_cover (assets/cover.png)。"
        update["retry_hint"] = "请重新生成游戏，或调整素材后再试。"
        return update

    graph_module = importlib.import_module("agent.generation_graph.graph")
    monkeypatch.setattr(graph_module, "validate_final_delivery", reject_without_repair)
    fixture = _load_generation_fixture(tmp_path)

    result = await generation_graph.ainvoke(fixture)

    assert result["generation_status"] == "failed"
    assert result["status"] == "failed"
    assert result["failed_step"] == "validator_agent"
    assert result["validation_report"]["valid"] is False
    assert result["error_message"]
    assert result["retry_hint"]
    assert any(log["level"] == "error" for log in result["agent_logs"])


async def test_generation_graph_repairs_once_after_validator_rejects_bundle(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    graph_module = importlib.import_module("agent.generation_graph.graph")
    fixture = _load_generation_fixture(tmp_path)
    validation_calls = {"count": 0}

    def reject_then_accept(state):
        validation_calls["count"] += 1
        if validation_calls["count"] == 1:
            return {
                "generation_status": "failed",
                "failed_step": "validator_agent",
                "error_message": "最终验收失败：external_cdn_detected (game.js)。",
                "retry_hint": "请根据 validation_report 调整素材或重试生成。",
                "validation_report": {
                    "valid": False,
                    "issues": [
                        {
                            "kind": "external_cdn_detected",
                            "path": "game.js",
                            "message": "External URL detected in static bundle.",
                        }
                    ],
                },
                "agent_logs": [
                    *state.agent_logs,
                    {
                        "step": "validator_agent",
                        "level": "error",
                        "message": "validator rejected first bundle",
                    },
                ],
            }
        return {
            "generation_status": "succeeded",
            "validation_report": {"valid": True, "issues": []},
            "artifact_result": {
                "workspace": state.artifact_workspace,
                "manifest_path": f"{state.artifact_workspace}/manifest.json",
                "entry_path": f"{state.artifact_workspace}/index.html",
                "asset_paths": [],
                "cover_path": "assets/cover.png",
            },
            "draft_game_meta": {
                "title": state.game_plan.get("title", ""),
                "description": state.game_plan.get("introduction", ""),
                "tags": state.game_plan.get("tags", []),
                "cover_path": "assets/cover.png",
                "manifest_path": "manifest.json",
                "entry_path": "index.html",
            },
            "agent_logs": [
                *state.agent_logs,
                {
                    "step": "validator_agent",
                    "level": "info",
                    "message": "validator accepted repaired bundle",
                },
            ],
        }

    monkeypatch.setattr(graph_module, "validate_final_delivery", reject_then_accept)

    result = await generation_graph.ainvoke(fixture)

    assert validation_calls["count"] == 2
    assert result["generation_status"] == "succeeded"
    assert result["status"] == "succeeded"
    assert result["validation_report"]["valid"] is True
    assert result["coding_repair_attempt_count"] == 1
    assert any(
        log["step"] == "coding_agent.repair_code"
        and "validation_report" in log["message"]
        for log in result["agent_logs"]
    )
